name: Unit Tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    # Define Redis as a service container
    services:
      redis:
        image: redis
        # Map port 6379 on the container to 6379 on the host machine
        ports:
          - 6379:6379
        # Health check to ensure Redis is up before tests run
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      REDIS_HOST: localhost
      REDIS_PORT: 6379

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # You can change this to your preferred version
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest # Ensures pytest is available even if not in requirements.txt

      - name: Create .env file
        run: |
          echo "DATABASE_URL=sqlite+aiosqlite:///:memory:" >> .env
          echo "JWT_SECRET=23oiefnergoiejrgio" >> .env

          echo "MAIL_USERNAME=$testusername@mail.com" >> .env
          echo "MAIL_FROM_NAME=$donotreply" >> .env
          echo "MAIL_PASSWORD=secretsMAIL_PASSWORD" >> .env
          echo "MAIL_FROM=brianobot9@gmail.com" >> .env
          echo "MAIL_PORT=465" >> .env
          echo "MAIL_SERVER=smtp.gmail.com" >> .env


      - name: Run Tests
        run: |
          mkdir logs
          pytest -s

  create_pull_request:
      runs-on: ubuntu-latest
      needs: test  # This creates the dependency link
      if: github.actor == 'brianobot'
      permissions:
        contents: write
        pull-requests: write
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Create Pull Request
          run: |
            # Check if a PR already exists from dev to master
            PR_EXISTS=$(gh pr list --head dev --base master --state open --json number -q '.[0].number')

            if [ -z "$PR_EXISTS" ]; then
              echo "No open PR found. Creating a new one..."
              gh pr create \
                --head dev \
                --base master \
                --title "Auto-PR: Dev to Master" \
                --body "Automated PR triggered by push from ${{ github.actor }}" \
                --assignee "${{ github.actor }}"
            else
              echo "PR already exists: #$PR_EXISTS. Skipping creation."
            fi
